### PR TITLE
Some cleanups

### PR DESCRIPTION
**Pull request by bajo**

### CODE REVIEW

**Comment by bajo** [comment]
More changes coming

**Comment by bajo** [comment]
The mentioned changes were not needed. Was another issue.

**Comment by ipa-nhg** [comment]
@bajo I suppose he also have to clean the bringup launch files to don't include the dynamixel control and the tilt/pan controller anymore? also the URDF files where the pan_tilt are included, right now only the tuw-robotino2 is correct. uibk and alufr will get also the shell?

**Review by ipa-nhg — APPROVED** [review]

**Comment by bajo** [comment]
@ipa-nhg Yes, at some point this needs to be removed from all the other robots.

**Review by ipa-nhg — APPROVED** [review]

**Pull request merged**
