### PR TITLE
Throttling commands to base from arm controller write function

### PR DESCRIPTION
**Pull request by tpatten**
Throttling commands to move base within the write function. No longer need the second call back function. Works with the Vienna robot, @lokalmatador we can test this tomorrow with the Innsbruck robot.

### CODE REVIEW

**Comment by ghost** [comment]
Yep, already sitting next to the little cyber buddy preparing things for the meeting (which is updating and compiling). Are there any special branches I need to run things?

**Comment by ipa-nhg** [comment]
tested and working?

**Comment by tpatten** [comment]
We ended up making other changes to the arm controller so I think this is now obsolete. @lokalmatador should we still try to throttle the commands, or can we safely assume that any array of inputs are published to twist mux at an acceptable rate? So far the hardware tests have been fine .

**Comment by ghost** [comment]
I guess it's fine the way it is. After all, I assume it was not even related to throttling or not, just the fact that ROS control executed it's natural behavior by approaching the last set point.
I'll create the merge request tomorrow after cleaning the code.

**Comment by tpatten** [comment]
We still had the issue of sending only the first base destination from any command. But that is fixed now.

**Comment by ghost** [comment]
So I can create the pull request, right?

**Comment by tpatten** [comment]
If you mean what we had working yesterday then yes.

**Comment by ghost** [comment]
Exactly.

**Comment by ipa-nhg** [comment]
out-of-date , updated by https://github.com/squirrel-project/squirrel_driver/pull/164

**Pull request closed without merging**
